#!/bin/sh
set -e

# PHP-FPM test based on mod-php test
# Author: Neal Gompa <ngompa13@gmail.com>

cat > /var/www/html/hello.php <<EOT
<?php echo "Hello, world!\n"; ?>
EOT

# Make sure that any CGI mechanism is disabled, since we want to test mod_php
# mode here.
a2dismod actions 2>/dev/null || true
a2dismod cgi 2>/dev/null || true
a2disconf php@PHP_VERSION@-cgi 2>/dev/null || true

# Ensure that mod_php is disabled
a2dismod php@PHP_VERSION@ 2>/dev/null

# php-fpm configuration requires mod_proxy_fcgi
a2enmod proxy_fcgi
a2enconf php@PHP_VERSION@-fpm
service apache2 restart 2>/dev/null
result=`wget -O- http://localhost/hello.php 2>/dev/null`
test "$result" = "Hello, world!"
