gd.lo: /home/ondrej/Projects/pkg-php/php-src/ext/gd/gd.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/home/ondrej/Projects/pkg-php/php-src/ext/gd $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ondrej/Projects/pkg-php/php-src/ext/gd/gd.c -o gd.lo 
gd_compat.lo: /home/ondrej/Projects/pkg-php/php-src/ext/gd/gd_compat.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/home/ondrej/Projects/pkg-php/php-src/ext/gd $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ondrej/Projects/pkg-php/php-src/ext/gd/gd_compat.c -o gd_compat.lo 
$(phplibdir)/gd.la: ./gd.la
	$(LIBTOOL) --mode=install cp ./gd.la $(phplibdir)

./gd.la: $(shared_objects_gd) $(GD_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_gd) $(GD_SHARED_LIBADD)

